Repository enhavo/enhavo, pull requests merged in 2021-04, with the labels that each got.

#1194 Fix form batch
  assets/node_modules/@enhavo/app/services/batch.yaml
Labels: backport-0.9

#1200 Fix empty navigation model
  src/Enhavo/Bundle/NavigationBundle/Form/Type/NodeCollectionType.php
Labels: backport-0.9

#1202 [AppBundle]Fixed ModalController formAction ignoring parameter template from route
  src/Enhavo/Bundle/AppBundle/Controller/ModalController.php
Labels: backport-0.9

#1206 [AppBundle/MultiTenancyBundle] Updated all filters to allow dot property path notation
  src/Enhavo/Bundle/AppBundle/Filter/Type/BooleanType.php
  src/Enhavo/Bundle/AppBundle/Filter/Type/OptionType.php
  src/Enhavo/Bundle/AppBundle/Filter/Type/TextType.php
  src/Enhavo/Bundle/MultiTenancyBundle/Filter/TenancyFilterType.php
Labels: backport-0.9

#1212 [FormBundle] BooleanType readonly/disabled
  assets/node_modules/@enhavo/form/assets/styles/module/_icheck.scss
  assets/node_modules/@enhavo/form/type/CheckboxType.ts
Labels: backport-0.9

#1217 Article repository bugfix
  src/Enhavo/Bundle/ArticleBundle/Repository/ArticleRepository.php
Labels: backport-0.9

#1216 [AppBundle] Added callback functionality to FilterQuery
  src/Enhavo/Bundle/AppBundle/Filter/FilterQuery.php
  src/Enhavo/Bundle/AppBundle/Filter/FilterQueryOr.php
Labels: backport-0.9

#1220 Fix reapply translation type
  src/Enhavo/Bundle/TranslationBundle/Form/EventListener/ReplaceTranslationTypeListener.php
Labels: backport-0.9

#1224 Use 0.9 branch for subtree split and 0.10 for backport
  .github/mergify.yml
  .github/workflows/subtree.yml
Labels: backport-0.9

#1225 Fix release workflow
  .github/workflows/release.yml
  assets/node_modules/@enhavo/app/.github/workflows/release.yml
  assets/node_modules/@enhavo/app/.gitignore
  assets/node_modules/@enhavo/article/.github/workflows/release.yml
  assets/node_modules/@enhavo/article/.gitignore
  assets/node_modules/@enhavo/block/.github/workflows/release.yml
  assets/node_modules/@enhavo/block/.gitignore
  assets/node_modules/@enhavo/calendar/.github/workflows/release.yml
  assets/node_modules/@enhavo/calendar/.gitignore
  assets/node_modules/@enhavo/contact/.gitignore
  assets/node_modules/@enhavo/content/.gitignore
  assets/node_modules/@enhavo/core/.github/workflows/release.yml
  assets/node_modules/@enhavo/core/.gitignore
  assets/node_modules/@enhavo/dashboard/.github/workflows/release.yml
  assets/node_modules/@enhavo/dashboard/.gitignore
  assets/node_modules/@enhavo/dependency-injection/.github/workflows/release.yml
  assets/node_modules/@enhavo/dependency-injection/.gitignore
  assets/node_modules/@enhavo/form/.github/workflows/release.yml
  assets/node_modules/@enhavo/form/.gitignore
  assets/node_modules/@enhavo/media/.github/workflows/release.yml
  assets/node_modules/@enhavo/media/.gitignore
  assets/node_modules/@enhavo/multi-tenancy/.github/workflows/release.yml
  assets/node_modules/@enhavo/multi-tenancy/.gitignore
  assets/node_modules/@enhavo/newsletter/.github/workflows/release.yml
  assets/node_modules/@enhavo/newsletter/.gitignore
  assets/node_modules/@enhavo/search/.gitignore
  assets/node_modules/@enhavo/shop/.github/workflows/release.yml
  assets/node_modules/@enhavo/shop/.gitignore
  assets/node_modules/@enhavo/slider/.github/workflows/release.yml
  assets/node_modules/@enhavo/slider/.gitignore
  assets/node_modules/@enhavo/theme/.github/workflows/release.yml
  assets/node_modules/@enhavo/theme/.gitignore
  assets/node_modules/@enhavo/translation/.github/workflows/release.yml
  assets/node_modules/@enhavo/translation/.gitignore
  assets/node_modules/@enhavo/user/.github/workflows/release.yml
  assets/node_modules/@enhavo/user/.gitignore
  assets/node_modules/@enhavo/vue-form/.github/workflows/release.yml
  assets/node_modules/@enhavo/vue-form/.gitignore
Labels: backport-0.10, backport-0.9

#1227 Add confirm delete option to PolyCollectionType
  assets/node_modules/@enhavo/form/loader/PolyCollectionLoader.ts
  assets/node_modules/@enhavo/form/services/loader.yaml
  assets/node_modules/@enhavo/form/type/PolyCollectionConfig.ts
  assets/node_modules/@enhavo/form/type/PolyCollectionItem.ts
  assets/node_modules/@enhavo/form/type/PolyCollectionType.ts
  src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.de.yml
  src/Enhavo/Bundle/AppBundle/Resources/translations/javascript.en.yml
  src/Enhavo/Bundle/FormBundle/Form/Type/PolyCollectionType.php
Labels: backport-0.10

#1230 Fix translation extension
  src/Enhavo/Bundle/TranslationBundle/Form/Extension/TranslationExtension.php
Labels: backport-0.10

#1234 Missing icons css load
  assets/node_modules/@enhavo/app/assets/styles/_blueprints.scss
  assets/node_modules/@enhavo/app/assets/styles/components/_view.scss
  assets/node_modules/@enhavo/form/assets/styles/module/_select2.scss
Labels: backport-0.10

#1233 Modal btn fix
  assets/node_modules/@enhavo/app/view/components/ViewComponent.vue
Labels: backport-0.10, backport-0.9

#1238 Implement VueForm submitData
  src/Enhavo/Bundle/VueFormBundle/Form/VueForm.php
  src/Enhavo/Bundle/VueFormBundle/Tests/Form/VueFormTest.php
  src/Enhavo/Bundle/VueFormBundle/Tests/Form/VueTypeTestTrait.php
Labels: backport-0.10
