Repository enhavo/enhavo, pull requests merged in 2022-06, with the labels that each got.

#1591 remove stringify function in submitAsync function
  assets/node_modules/@enhavo/vue-form/form/Form.ts
Labels: backport-0.10

#1594 [App] Added events to minimize/maximize view
  assets/node_modules/@enhavo/app/view-stack/ViewStack.ts
  assets/node_modules/@enhavo/app/view-stack/components/ViewComponent.vue
  assets/node_modules/@enhavo/app/view-stack/event/MaximizeEvent.ts
  assets/node_modules/@enhavo/app/view-stack/event/MinimizeEvent.ts
Labels: backport-0.9, backport-0.10

#1597 [App] Added events to minimize/maximize view
  assets/node_modules/@enhavo/app/view-stack/ViewStack.ts
  assets/node_modules/@enhavo/app/view-stack/components/ViewComponent.vue
  assets/node_modules/@enhavo/app/view-stack/event/MaximizeEvent.ts
  assets/node_modules/@enhavo/app/view-stack/event/MinimizeEvent.ts
Labels: backport-0.9
